name: Release

on:
    push:
        tags: '*'

permissions:
  id-token: write  # Required for trusted publishing
  contents: read

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm test
            - run: npm publish
